--**Numpy**--

In [1]:
import numpy as np

In [17]:
a = np.arange(5)
b = np.arange(10)

In [18]:
a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a = np.arange(20).reshape(4,5)

In [20]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(4, 5)
20
int64
8
<class 'numpy.ndarray'>


In [22]:
b = np.array( [4.0, 5.0, 6.0, 7.0] )
print(b)
print(b.dtype)
print(type(b))

[4. 5. 6. 7.]
float64
<class 'numpy.ndarray'>


In [23]:
c = np.eye(8)
dtype=np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
d = np.linspace(1, 3, 20, endpoint=True)
print(d)

[1.         1.10526316 1.21052632 1.31578947 1.42105263 1.52631579
 1.63157895 1.73684211 1.84210526 1.94736842 2.05263158 2.15789474
 2.26315789 2.36842105 2.47368421 2.57894737 2.68421053 2.78947368
 2.89473684 3.        ]


In [27]:
e = np.logspace(-1, 3, 15, endpoint=True, base=10)
print(e)

[1.00000000e-01 1.93069773e-01 3.72759372e-01 7.19685673e-01
 1.38949549e+00 2.68269580e+00 5.17947468e+00 1.00000000e+01
 1.93069773e+01 3.72759372e+01 7.19685673e+01 1.38949549e+02
 2.68269580e+02 5.17947468e+02 1.00000000e+03]


In [16]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [28]:
f = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
f

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

--**Array Operations**--

In [30]:
a = np.arange(14).reshape(5,5)
print(a)

ValueError: ignored

In [31]:
a*5

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [32]:
a + a*2

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [33]:
a*a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
b = a.transpose()
b

In [35]:
a @ b

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [36]:
print(a)
a.sum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [37]:
a.sum()

66

In [38]:
print(a.min(), a.max())

0 11


--**Universal Functions**--

In [39]:
b = a*np.pi/10.0
print(b)

[[0.         0.31415927 0.62831853 0.9424778 ]
 [1.25663706 1.57079633 1.88495559 2.19911486]
 [2.51327412 2.82743339 3.14159265 3.45575192]]


In [40]:
c = np.cos(b)
print(c)

[[ 1.00000000e+00  9.51056516e-01  8.09016994e-01  5.87785252e-01]
 [ 3.09016994e-01  6.12323400e-17 -3.09016994e-01 -5.87785252e-01]
 [-8.09016994e-01 -9.51056516e-01 -1.00000000e+00 -9.51056516e-01]]


In [41]:
d = b + c 

In [42]:
print(d)

[[1.         1.26521578 1.43733553 1.53026305]
 [1.56565406 1.57079633 1.5759386  1.61132961]
 [1.70425713 1.87637687 2.14159265 2.5046954 ]]


In [43]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
a[9]

9

In [48]:
print(a[8:2])

[]


In [50]:
a[1:3]

array([1, 2])

In [51]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
a = np.arange(18).reshape(2,9)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [60]:
a[1,1]

10

In [ ]:
a[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [ ]:
a[:,1]

array([ 1,  6, 11])

In [ ]:
a = a.flatten()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [61]:
for r in a:
    print(r)
a = np.arange(10).reshape(2,5)
print(a)

[0 1 2 3 4 5 6 7 8]
[ 9 10 11 12 13 14 15 16 17]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [62]:
for e in a.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9


In [64]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [65]:
b = a
b is a

True

In [68]:
b.shape = (10, 2)
print(b)
a.shape

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


(10, 2)

In [69]:
b is a

True

In [70]:
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [72]:
a = np.arange(16)
c = a[:]
a.shape = (8,2)

print(a)
print(c)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [73]:
c[1] = -1
print(a)
print(c)

[[ 0 -1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
d = c[3:8]
print(d)

[3 4 5 6 7]


In [ ]:
d[:] = 0 

In [ ]:
print(a)
print(c)
print(d)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[ 0 -1  2  0  0  0  0  0  8  9 10 11]
[0 0 0 0 0]


In [ ]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [ ]:
d = a.copy()
d[:,:] = 0.0
print(a)
print(d)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


--**Boolean Indexing**--

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[a > 4] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
a[a == 0] = -1
a

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [ ]:
a == -1

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a = np.arange(12).reshape(3,4)
a[np.logical_and(a > 3, a <= 9)] = 0.0
a

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11]])

In [ ]:
a > 4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [ ]:
M = 32
N = 64
xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, M, endpoint=False)
y = np.linspace(ymin, ymax, N, endpoint=False)

print(x.shape)
print(y.shape)
y

(32,)
(64,)


array([0.      , 0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125,
       0.09375 , 0.109375, 0.125   , 0.140625, 0.15625 , 0.171875,
       0.1875  , 0.203125, 0.21875 , 0.234375, 0.25    , 0.265625,
       0.28125 , 0.296875, 0.3125  , 0.328125, 0.34375 , 0.359375,
       0.375   , 0.390625, 0.40625 , 0.421875, 0.4375  , 0.453125,
       0.46875 , 0.484375, 0.5     , 0.515625, 0.53125 , 0.546875,
       0.5625  , 0.578125, 0.59375 , 0.609375, 0.625   , 0.640625,
       0.65625 , 0.671875, 0.6875  , 0.703125, 0.71875 , 0.734375,
       0.75    , 0.765625, 0.78125 , 0.796875, 0.8125  , 0.828125,
       0.84375 , 0.859375, 0.875   , 0.890625, 0.90625 , 0.921875,
       0.9375  , 0.953125, 0.96875 , 0.984375])

In [ ]:
import time
import numpy as np
M = 32
N = 64

x = np.linspace(0.0, 1.0, M, endpoint=False)
y = np.linspace(0.0, 1.0, N, endpoint=False)


In [ ]:
t0 = time.time()

g = np.zeros((M, N))

for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.049758195877075195 s


In [ ]:
x2d, y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [ ]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0014040470123291016 s


--**Concatenation of arrays**--

In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([4, 3, 2, 1])
np.concatenate([y,x])

array([4, 3, 2, 1, 1, 2, 3, 4])

In [ ]:
z = [9, 4, 6]
print(np.concatenate([x, y, z]))

[1 2 3 4 4 3 2 1 9 4 6]


In [ ]:
grid = np.array([[10, 20, 30],
                 [40, 50, 60]])

In [ ]:
np.concatenate([grid, grid])

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.concatenate([grid, grid], axis=1)

array([[10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60]])

--**Splitting of arrays**--

In [79]:
x = [8, 7, 6, 5, 4, 7 ,5, 2, 1, 6 ,9]
x1, x2, x3,x4 = np.split(x, [3, 5,8])
print(x1, x2, x3, x4)

[8 7 6] [5 4] [7 5 2] [1 6 9]


In [81]:
grid = np.arange(20).reshape((4, 5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [82]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]


--**Aggregates**--

In [75]:
x = np.arange(-2, 19)
print(x)
np.add.reduce(x)

[-2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


168

In [76]:
np.multiply.reduce(x)

0

In [77]:
np.add.accumulate(x)

array([ -2,  -3,  -3,  -2,   0,   3,   7,  12,  18,  25,  33,  42,  52,
        63,  75,  88, 102, 117, 133, 150, 168])

In [78]:
np.multiply.accumulate(x)

array([-2,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0])